<?php

declare(strict_types=1);

return [
    ['method' => 'GET',  'pattern' => '/',                    'controller' => 'PublicController',    'action' => 'home'],
    ['method' => 'GET',  'pattern' => '/login',               'controller' => 'AuthController',      'action' => 'login'],
    ['method' => 'POST', 'pattern' => '/login',               'controller' => 'AuthController',      'action' => 'doLogin'],
    ['method' => 'GET',  'pattern' => '/registro',            'controller' => 'AuthController',      'action' => 'registro'],
    ['method' => 'POST', 'pattern' => '/registro',            'controller' => 'AuthController',      'action' => 'doRegistro'],
    ['method' => 'POST', 'pattern' => '/logout',              'controller' => 'AuthController',      'action' => 'logout'],
    ['method' => 'GET',  'pattern' => '/recuperar-contrasena', 'controller' => 'AuthController',      'action' => 'solicitarResetPassword'],
    ['method' => 'POST', 'pattern' => '/recuperar-contrasena', 'controller' => 'AuthController',      'action' => 'solicitarResetPassword'],
    ['method' => 'GET',  'pattern' => '/restablecer-contrasena', 'controller' => 'AuthController',    'action' => 'resetPassword'],
    ['method' => 'POST', 'pattern' => '/restablecer-contrasena', 'controller' => 'AuthController',    'action' => 'resetPassword'],
    ['method' => 'GET',  'pattern' => '/dashboard',           'controller' => 'DashboardController', 'action' => 'index'],
    ['method' => 'GET',  'pattern' => '/perfil',              'controller' => 'PerfilController',    'action' => 'index'],
    ['method' => 'POST', 'pattern' => '/perfil',              'controller' => 'PerfilController',    'action' => 'actualizar'],

    ['method' => 'GET',  'pattern' => '/documentos',          'controller' => 'DocumentoController',  'action' => 'index'],
    ['method' => 'GET',  'pattern' => '/documentos/subir',    'controller' => 'DocumentoController',  'action' => 'subir'],
    ['method' => 'POST', 'pattern' => '/documentos/subir',    'controller' => 'DocumentoController',  'action' => 'subir'],
    ['method' => 'GET',  'pattern' => '/documentos/editar', 'controller' => 'DocumentoController', 'action' => 'editar'],
    ['method' => 'POST', 'pattern' => '/documentos/editar', 'controller' => 'DocumentoController', 'action' => 'editar'],
    ['method' => 'GET',  'pattern' => '/documentos/eliminar', 'controller' => 'DocumentoController', 'action' => 'eliminar'],
    ['method' => 'GET',  'pattern' => '/documentos/ver', 'controller' => 'DocumentoController',  'action' => 'ver'],
    ['method' => 'GET',  'pattern' => '/documentos/archivo', 'controller' => 'DocumentoController',  'action' => 'archivo'],
    ['method' => 'GET',  'pattern' => '/documentos/generales', 'controller' => 'DocumentoController',  'action' => 'generales'],
    ['method' => 'GET',  'pattern' => '/documentos/paciente', 'controller' => 'DocumentoController',  'action' => 'porPaciente'],

    ['method' => 'GET',  'pattern' => '/publico/doc',     'controller' => 'PublicController', 'action' => 'verDocumento'],
    ['method' => 'GET',  'pattern' => '/publico/archivo', 'controller' => 'PublicController', 'action' => 'archivo'],
    ['method' => 'GET',  'pattern' => '/publico/mis-documentos', 'controller' => 'PublicController', 'action' => 'misDocumentos'],
    ['method' => 'GET',  'pattern' => '/publico/encuesta', 'controller' => 'PublicController', 'action' => 'mostrarEncuesta'],
    ['method' => 'POST', 'pattern' => '/publico/encuesta',   'controller' => 'PublicController', 'action' => 'mostrarEncuesta'],


    ['method' => 'GET',  'pattern' => '/encuestas',              'controller' => 'EncuestaController',  'action' => 'index'],
    ['method' => 'GET',  'pattern' => '/encuestas/crear',        'controller' => 'EncuestaController',  'action' => 'crear'],
    ['method' => 'POST', 'pattern' => '/encuestas/crear',        'controller' => 'EncuestaController',  'action' => 'crear'],
    ['method' => 'GET',  'pattern' => '/encuestas/resultados', 'controller' => 'EncuestaController', 'action' => 'resultados'],

    ['method' => 'GET',  'pattern' => '/traslados',                 'controller' => 'TrasladoController',  'action' => 'index'],
    ['method' => 'GET',  'pattern' => '/traslados/nuevo',           'controller' => 'TrasladoController',  'action' => 'nuevo'],
    ['method' => 'POST', 'pattern' => '/traslados/nuevo',           'controller' => 'TrasladoController',  'action' => 'nuevo'],
    ['method' => 'GET',  'pattern' => '/traslados/ver',       'controller' => 'TrasladoController',  'action' => 'ver'],
    ['method' => 'GET',  'pattern' => '/traslados/actualizar-estado', 'controller' => 'TrasladoController', 'action' => 'actualizarEstado'],
    ['method' => 'POST', 'pattern' => '/traslados/actualizar-estado', 'controller' => 'TrasladoController', 'action' => 'actualizarEstado'],
    ['method' => 'GET',  'pattern' => '/traslados/historial',      'controller' => 'TrasladoController',  'action' => 'historial'],
    ['method' => 'GET',  'pattern' => '/traslados/mapa',            'controller' => 'UbicacionController', 'action' => 'mapa'],
    ['method' => 'GET',  'pattern' => '/traslados/tracking',        'controller' => 'UbicacionController', 'action' => 'conductorView'],
    ['method' => 'POST', 'pattern' => '/api/ubicacion',             'controller' => 'UbicacionController', 'action' => 'registrar'],
    ['method' => 'GET',  'pattern' => '/api/ubicaciones/activas',   'controller' => 'UbicacionController', 'action' => 'activas'],
    ['method' => 'GET',  'pattern' => '/api/ubicaciones/historial', 'controller' => 'UbicacionController', 'action' => 'historial'],
    ['method' => 'GET',  'pattern' => '/api/ubicaciones/stream',    'controller' => 'UbicacionController', 'action' => 'eventStream'],
    ['method' => 'GET',  'pattern' => '/api/traslados/activos',     'controller' => 'UbicacionController', 'action' => 'trasladosActivos'],
    ['method' => 'GET',  'pattern' => '/api/ruta/real',              'controller' => 'UbicacionController', 'action' => 'rutaReal'],

    ['method' => 'GET',  'pattern' => '/api/catalogo',              'controller' => 'TrasladoController',  'action' => 'apiCatalogo'],
    ['method' => 'GET',  'pattern' => '/api/pacientes',             'controller' => 'TrasladoController',  'action' => 'apiPacientes'],
    ['method' => 'GET',  'pattern' => '/api/copilotos',             'controller' => 'TrasladoController',  'action' => 'apiCopilotos'],
    ['method' => 'GET',  'pattern' => '/api/rutas-info',            'controller' => 'TrasladoController',  'action' => 'apiRutasInfo'],

    ['method' => 'GET',  'pattern' => '/conductores',           'controller' => 'ConductorController', 'action' => 'index'],
    ['method' => 'GET',  'pattern' => '/conductores/crear',     'controller' => 'ConductorController', 'action' => 'crear'],
    ['method' => 'POST', 'pattern' => '/conductores/crear',     'controller' => 'ConductorController', 'action' => 'guardar'],
    ['method' => 'GET',  'pattern' => '/conductores/editar',    'controller' => 'ConductorController', 'action' => 'editar'],
    ['method' => 'POST', 'pattern' => '/conductores/editar',    'controller' => 'ConductorController', 'action' => 'editar'],
    ['method' => 'POST', 'pattern' => '/conductores/desactivar', 'controller' => 'ConductorController', 'action' => 'desactivar'],
    ['method' => 'POST', 'pattern' => '/conductores/reactivar',  'controller' => 'ConductorController', 'action' => 'reactivar'],

    ['method' => 'GET',  'pattern' => '/rutas',                'controller' => 'RutaController', 'action' => 'index'],
    ['method' => 'GET',  'pattern' => '/rutas/crear',          'controller' => 'RutaController', 'action' => 'crear'],
    ['method' => 'POST', 'pattern' => '/rutas/crear',          'controller' => 'RutaController', 'action' => 'guardar'],

    ['method' => 'GET',  'pattern' => '/funcionarios',              'controller' => 'FuncionarioController', 'action' => 'index'],
    ['method' => 'GET',  'pattern' => '/funcionarios/crear',        'controller' => 'FuncionarioController', 'action' => 'crear'],
    ['method' => 'POST', 'pattern' => '/funcionarios/crear',        'controller' => 'FuncionarioController', 'action' => 'crear'],
    ['method' => 'GET',  'pattern' => '/funcionarios/editar',       'controller' => 'FuncionarioController', 'action' => 'editar'],
    ['method' => 'POST', 'pattern' => '/funcionarios/editar',       'controller' => 'FuncionarioController', 'action' => 'editar'],
    ['method' => 'POST', 'pattern' => '/funcionarios/desactivar',   'controller' => 'FuncionarioController', 'action' => 'desactivar'],
    ['method' => 'POST', 'pattern' => '/funcionarios/reactivar',    'controller' => 'FuncionarioController', 'action' => 'reactivar'],

    ['method' => 'GET',  'pattern' => '/pacientes/editar',     'controller' => 'PacienteController', 'action' => 'editar'],
    ['method' => 'POST', 'pattern' => '/pacientes/editar',     'controller' => 'PacienteController', 'action' => 'editar'],

    ['method' => 'GET',  'pattern' => '/offline',              'controller' => 'PublicController',  'action' => 'offline'],

    ['method' => 'GET',  'pattern' => '/noticias',             'controller' => 'NoticiaController', 'action' => 'index'],
    ['method' => 'GET',  'pattern' => '/noticias/crear',       'controller' => 'NoticiaController', 'action' => 'crear'],
    ['method' => 'POST', 'pattern' => '/noticias/crear',       'controller' => 'NoticiaController', 'action' => 'crear'],
    ['method' => 'GET',  'pattern' => '/noticias/editar',      'controller' => 'NoticiaController', 'action' => 'editar'],
    ['method' => 'POST', 'pattern' => '/noticias/editar',      'controller' => 'NoticiaController', 'action' => 'editar'],
    ['method' => 'GET',  'pattern' => '/noticias/eliminar',    'controller' => 'NoticiaController', 'action' => 'eliminar'],
    ['method' => 'GET',  'pattern' => '/noticias/toggle',      'controller' => 'NoticiaController', 'action' => 'toggle'],
];
